# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-30 05:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playlist',
            old_name='name',
            new_name='playlist_name',
        ),
        migrations.RenameField(
            model_name='playlist',
            old_name='tag',
            new_name='playlist_tag',
        ),
        migrations.RenameField(
            model_name='song',
            old_name='Playlist',
            new_name='playlist_song',
        ),
        migrations.AddField(
            model_name='song',
            name='song_dur',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='song',
            name='song_name',
            field=models.CharField(default=None, max_length=256),
        ),
    ]
