# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-03 08:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20170402_0751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='playlist_song',
            field=models.CharField(default='NA', max_length=256),
        ),
    ]
